### ISSUE TITLE
Please support ipv6

### ISSUE THREAD

**Issue by jiangz00** [drittich/DnsTube#10]

**Comment by drittich** [comment]
I'll look into adding this in the next day or so, but my modem does not support ipv6. Maybe you can do some testing for me?

**Comment by jiangz00** [comment]
可以呀，但我不知道如何帮助你

**Comment by drittich** [comment]
I'll let you know when it's ready for testing.

**Comment by jiangz00** [comment]
ok

**Comment by drittich** [comment]
Beta version with support for IPv6 has been released. Let me know how it works for you: https://github.com/drittich/DnsTube/releases/tag/v0.6.0b

**Comment by leviacn** [comment]
it work perfect. thx.

**Comment by jiangz00** [comment]
谢谢
