### ISSUE TITLE
DnsTube does not allow for scoped tokens

### ISSUE THREAD

**Issue by Rovoska** [drittich/DnsTube#11]
I am trying to use a token that is scoped for a single domain, but the program insists I allow all zones, something that I'd rather not have. Please allow for this, thanks.

**Comment by drittich** [comment]
Thanks for the feedback. I have not experimented with multiple zones, yet. What is the output when you use a token scoped to one domain?

**Comment by Rovoska** [comment]
Error fetching list:unable to list zones. Token permissins should be similar to [All zones - Zone:Read, DNS:Edit]

**Comment by drittich** [comment]
Ability to specifiy Zone IDs to update added in [release v0.7.0].(https://github.com/drittich/DnsTube/releases/tag/v0.7.0)
