### ISSUE TITLE
A record gets changed to AAAA when updating both IPv4 and IPv6 addresses

### ISSUE THREAD

**Issue by hazardmy** [drittich/DnsTube#13]
As stated in the title, my A records got changed to AAAA when I update both IPv4 and IPv6 using the latest DNSTube release.

**Comment by XXLPoseidon** [comment]
Had the same problem

**Comment by drittich** [comment]
Thanks for the report, I'll take a look.

**Comment by drittich** [comment]
I see the issue, should have a fix for it later today.

**Comment by drittich** [comment]
Fixed in release [v0.7.3](https://github.com/drittich/DnsTube/releases/tag/v0.7.3) - any issues, let me know.

**Comment by hazardmy** [comment]
Thank you for the fast response! Will test it once I'm back home
