### ISSUE TITLE
How to use custom url to get IP address?

### ISSUE THREAD

**Issue by opz20** [drittich/DnsTube#17]
How to use custom url to get IP address?

**Comment by drittich** [comment]
There is currently no way to do this. Are you having an issue with the API DnsTube uses currently?

**Comment by kurtnelle** [comment]
1. Modify the code
2. Add the new URL
3. Compile.

God Bless Open source.

**Comment by opz20** [comment]
> There is currently no way to do this. Are you having an issue with the API DnsTube uses currently?

Yes. In my network environment, this IP resolution link seems to be going to the proxy network, so my IP address cannot be correctly identified.

**Comment by opz20** [comment]
> 1. Modify the code
> 2. Add the new URL
> 3. Compile.
> 
> God Bless Open source.

I found another solution, just add the URL to the whitelist, thank you for your suggestion

**Comment by opz20** [comment]
> > There is currently no way to do this. Are you having an issue with the API DnsTube uses currently?
> 
> Yes. In my network environment, this IP resolution link seems to be going to the proxy network, so my IP address cannot be correctly identified.

Now the problem has shifted to an error "Exception of type 'System.Exception' was thrown."

**Comment by opz20** [comment]
[Issue 15](https://github.com/drittich/DnsTube/issues/15) It seems that my TLD does not support the free plan. I have replaced the DDNS service provider and the problem is solved,thanks for help.
