### ISSUE TITLE
2 computers sync to same domain name possible?

### ISSUE THREAD

**Issue by chuccck** [drittich/DnsTube#19]
First thanks for the effort, I hate duckdns and this finally helped me get rid of it for most of the services I have running. 

I have another computer that is behind a VPN so it has a different external ip address.  Is it possible to run DnsTube on it but have it sync to the same domain as my other computers but as a subdomain/CNAME?  for example, could it update the target of vpn.mydomain.com in Cloudflare's DNS?  Or maybe i set up vpn.mydomain.com as an A record?  (sorry, just brushing the surface on this)

**Comment by kurtnelle** [comment]
Running it on multiple machines should not be a problem. Test it out and let us know :)

**Comment by chuccck** [comment]
> Running it on multiple machines should not be a problem. Test it out and let us know :)

where i get stuck is directing it to a specific record on my domain.  And should vpn.mydomain,com be a cname or A record?

**Comment by crazyrabbit0** [comment]
If I've got what you mean right, you should:

- Set vpn.yourdomain.com in cloudflare as an A record,
with the current IP of the VPN protected computer

- Refresh DnsTube

- Select vpn.yourdomain.com within DnsTube on the VPN protected computer

**Comment by drittich** [comment]
The above should work fine. Note the checkbox beside the entries in DnsTube. On the VPN machine, only check the box next to vpn.yourdomain.com. On the other computer(s), you would not check vpn.yourdomain.com.
