### ISSUE TITLE
System.Exception when updating (Using Global API Key)

### ISSUE THREAD

**Issue by crazyrabbit0** [drittich/DnsTube#20]
The updater has stopped working,
throwing error:

> Error updating [sub.examle.com] in zone [examle.com] to xx.xxx.xxx.xxx
> Exception of type 'System.Exception' was thrown.

I have tried disabling the Windows Firewall and Running as Administrator,
doesn't seem to affect it.

---

I also tried the API Token option,
getting another error:

> Error fetching list: Unable to list DNS records. If you are updating all zones, token permissions should be similar to [All zones - Zone:Read, DNS:Edit]. If your token only has permissions for specific zones, click Settings and configure the Zone IDs with a comma-separated list.

Although I have the appropriate settings in the token:
![image](https://user-images.githubusercontent.com/5244848/85863222-883a7d00-b7cb-11ea-987e-6ba7593b6ab3.png)

**Comment by drittich** [comment]
What TLD are you trying to update?

**Comment by crazyrabbit0** [comment]
> What TLD are you trying to update?

I'm currently using a .ml domain

**Comment by drittich** [comment]
I can't explain the .eu issue, but all of the other domains are not supported. See this for details: https://community.cloudflare.com/t/unable-to-update-ddns-using-api-for-some-tlds/167228/52

**Comment by crazyrabbit0** [comment]
> I can't explain the .eu issue, but all of the other domains are not supported (although it may work with a paid plan). See this for details: https://community.cloudflare.com/t/unable-to-update-ddns-using-api-for-some-tlds/167228/52

Oh ok, didn't know about this new restriction,
this sucks for me, I guess i have to buy a .com and work with many subdomains instead.

Thanks for everything!
