### ISSUE TITLE
little suggestion about way to detect ipv4 and ipv6 address

### ISSUE THREAD

**Issue by smilelc3** [drittich/DnsTube#21]
DnsTube is a fancy tool. There is a thing that I think can do better.
I learn that you use 'whatismyipaddress.com' web api to get public IP address, as following code :  
> var url = protocol == IpSupport.IPv4 ? "http://ipv4bot.whatismyipaddress.com" : "http://ipv6bot.whatismyipaddress.com";

but `whatismyipaddress.com` web may not suit for global-users. In my case(China), `test-ipv6.com` give a More accurate result when `whatismyipaddress.com` show "ipv6 is not detected“. so if this tool can supply a second method to get public ip(s), especially ipv6.

**Comment by drittich** [comment]
Thanks for the feedback! Yes, I plan to make this configurable, with an optional RegEx you provide to specify how to extract the output from the result.

**Comment by kurtnelle** [comment]
Except that test-ipv6.com is a vastly more complex way to get that IP address. The proper way to extract that info would be to parse the HTML (with HTML agility pack) use a xpath to get to the relevant node, then parse the IP out with IPAddress.Parse

**Comment by s0urc3-ray** [comment]
@drittich Is there any reason why this project does not have it's own IPv4/v6 script running via GitHub Pages?

**Comment by drittich** [comment]
@s0urc3-ray Nice idea! I'll look into that.

**Comment by s0urc3-ray** [comment]
Happy New Year Everybody!

@drittich Thanks! I hope it works well with GitHub's CDN which should offer vastly lower latency for most users?

> EDIT: Sorry I was mistaken. That test-ipv6.com site requires javascript! It cannot work with DnsTube.

@kurtnelle This really surprised me, how could JavaScript be required for such a simple task... so as I was bored I decided to investigate the site and Discovered how unique and extensive it's testing actually is. That said, I couldn't find my IPv6 Address despite it saying I had a 10/10 Score 😞 

A few minutes later I had the IPv6 Address Lookup URL which is https://ipv6.vm3.test-ipv6.com/ip/ and returns the following: `callback({"ip":"2a00:2***:****:****:****:****:****:****, 2a00:2***:****:****:****:****:****:****","type":"ipv6","subtype":"","via":"","padding":""})`

It does seem very unreliable as well, I had requests failing. And why does it return the via and padding variables? 😕

**Comment by kurtnelle** [comment]
@s0urc3-ray, Looks like you found their magic source. Great job. Just for completeness to get the ipv4 address its: https://ipv4.vm3.test-ipv6.com/ip/
The requests failing thing may just be a rate limiter preventing multiple requests from the same IP to often.

**Comment by drittich** [comment]
@s0urc3-ray I have no experience with GitHub Pages, but from a few minutes browsing the docs I don't see any way to get the IP address without using JavaScript. Do you have an example?

**Comment by s0urc3-ray** [comment]
@drittich Forgive me, I presumed GitHub would allow Basic Code Execution. Instead of GitHub Pages I now have to Recommend CloudFlare Workers that Do Run Server Side Code. 100,000 Requests a Day per Worker Domain on a Free Account, Will this be enough requests? Does CloudFlare have a secret plan for Open Source Software?

I'm putting together an example IPv4/IPv6 Lookup Worker now and will Reply shortly with the URL and the Workers Code.

Anybody could create their own Mirror of this Code on their own CloudFlare Account, then enter the Worker URL into DnsTube if the Requests Limit is too low for just one Worker URL to handle all of DnsTubes Requests.

**Comment by drittich** [comment]
My plan is to add config variables for URLs and regex parse patterns, so you can use the endpoint of your choice.

**Comment by kurtnelle** [comment]
@drittich, In stead of configuration perhaps a IQueryIP interface?
