### ISSUE TITLE
Not all Domains/Zones are fetched in DnsTube

### ISSUE THREAD

**Issue by KrzysztofMaciejewskiCOM** [drittich/DnsTube#22]
Hi.

There is a problem with number of fetch dns zones. I have over 60 domains in Cloudflare. DnsTube fetch and update about 50.
Cant see all domain in list in DnsTube.
Problem exist in latest stable and pre-release.

Thanks

**Comment by drittich** [comment]
Thanks for the report, I'll check it out - sounds like Cloudflare does paging in their API.

**Comment by kurtnelle** [comment]
@drittich, Do you know if Cloudflare has a simulator that can reproduce that problem. I'd hate to have to set up 65 domains just to test the paging.

**Comment by KrzysztofMaciejewskiCOM** [comment]
if there is anything i can help, please tell me
Thanks for your quick support @drittich

**Comment by drittich** [comment]
Cloudflare does paging, should not be too hard for me to make some changes, stand by.

**Comment by drittich** [comment]
@KrzysztofMaciejewskiCOM I've implemented Cloudflare API paging, please give it a try with this release: https://github.com/drittich/DnsTube/releases/download/v0.8.0-beta2/DnsTube-Portable-beta2.7z

**Comment by KrzysztofMaciejewskiCOM** [comment]
> @KrzysztofMaciejewskiCOM I've implemented Cloudflare API paging, please give it a try with this release: https://github.com/drittich/DnsTube/releases/download/v0.8.0-beta2/DnsTube-Portable-beta2.7z
> 
> It's a portable release, so looks for the config.json in the same folder as the application. You can copy your old config.json (the path to it is shown in the lower pane when you run the non-portable version).

GREAT!
seems works OK! Thank you so much!

**Comment by drittich** [comment]
Happy to help @KrzysztofMaciejewskiCOM .
