### ISSUE TITLE
[Feature Request] Option for network proxy

### ISSUE THREAD

**Issue by LinEvil** [drittich/DnsTube#28]
Can you add an option to toggle the system proxy?
Or an option to customize the proxy server.

This is useful for my complex network environment (:

**Comment by drittich** [comment]
I'll add this to my backlog and let you know when there is a version for you to try.

**Comment by drittich** [comment]
@LinEvil Not sure if this is still something you are looking for, but can you explain your use case? E.g., it's not clear to me how your public IP would be obtained if you are going through a web proxy.

**Comment by drittich** [comment]
Closing until I can get a use case for this.
