### ISSUE TITLE
Error getting public IPv4

### ISSUE THREAD

**Issue by nokemono** [drittich/DnsTube#29]
I was able to use it until now, but now I get an error message.

Error getting public IPv4: One or more errors occurred. (The requested name is valid, but no data of the requested type was found. (ipv4bot.whatismyipaddress.com:80))

**Comment by PewQuadrat** [comment]
The used API is no longer valid: https://whatismyipaddress.com/api

**Comment by drittich** [comment]
I'll be releasing a fix shortly.

**Comment by drittich** [comment]
The latest release should solve this: https://github.com/drittich/DnsTube/releases/tag/v0.8.2
