### ISSUE TITLE
It doesnt run while wait for asking update

### ISSUE THREAD

**Issue by tungnb** [drittich/DnsTube#32]
Hi,
Thank for amazing app. I used it for along time and it really good.
So I don't want to update. But, after my computer reset, It doesn't run because waiting for asking update.
So pls help me to run while asking. And if possible, turn off check for update too.
Thank you so much!

**Comment by drittich** [comment]
Good point, I should not block running with that. I'll look into fixing that.

In the meantime, you can disable the check for update in the Settings menu:
![image](https://user-images.githubusercontent.com/1222810/142806217-93fd29f4-d578-433d-ac62-b950a2bf6ca4.png)

**Comment by drittich** [comment]
This is fixed in [release v0.9.1](https://github.com/drittich/DnsTube/releases/tag/v0.9.1)
