### ISSUE TITLE
TTL

### ISSUE THREAD

**Issue by darkjacky** [drittich/DnsTube#33]
Update address now seems to edit the TTL of everything it touches from whatever it is to Auto. This is unwanted behavior IMO.
Any way to fix that?

**Comment by drittich** [comment]
I'll check it out!

**Comment by drittich** [comment]
Fixed in [release v0.9.2](https://github.com/drittich/DnsTube/releases/tag/v0.9.2)

**Comment by darkjacky** [comment]
Confirmed fixed.

Thank you!
