### ISSUE TITLE
settings dialog sizing issue

### ISSUE THREAD

**Issue by ScottFerg56** [drittich/DnsTube#34]
Thanks for DnsTube! Just updated to v0.9.2.
The settings dialog now shows the edit controls as thin horizontal slivers. Some kind of sizing issue. See image.

Running Windows 10 Pro 21H1, dual 32" 3840x2160 monitors at 150%. Tried setting down to 100% and restarting DnsTube without effect.

![Clipboard Image (1)](https://user-images.githubusercontent.com/11354336/145113560-4530251a-9600-4cfc-abe8-fbd65be39f1e.png)
.

**Comment by drittich** [comment]
Interesting. I'll try to reproduce and get back to you, but all looks good
here. Thanks for troubleshooting.

**Comment by ScottFerg56** [comment]
I should be able to build and debug here at some point. Note that your README states DnsTube uses .NET 5 and builds with VS 2019. But it actually required .NET 6, which also implies VS 2022. So my build/debug will have to wait until I update to 2022.
No worries as it's working fine and I have the workaround; assuming I can find the settings file.
Thanks again!

**Comment by drittich** [comment]
The settings file location is logged in the main interface when you first
launch it.

**Comment by drittich** [comment]
Good news, I've reproduced the problem on another machine. I also observed you can't see where the settings are stored because it short-circuits when you have not set things up yet, so apologies. Should have a fix shortly.

**Comment by drittich** [comment]
@ScottFerg56  I've got a fix here: [release DnsTube v0.9.3](https://github.com/drittich/DnsTube/releases/tag/untagged-4e09d6f33547977a8f8a). Let me know how it works for you.

**Comment by ScottFerg56** [comment]
That link gets me a 404: page not found.

**Comment by drittich** [comment]
Whoops, try again.

**Comment by ScottFerg56** [comment]
Looks great!
Thanks for your responsiveness! As a fellow C# developer of freeware I understand and appreciate your effort. DnsTube is doing its part keeping my website alive with a dynamic IP thru Cloudflare: [Forest Moon](http://www.forestmoon.com/)

**Comment by drittich** [comment]
That's uncommonly kind Scott, made my day. And, I am more than a little fascinated with your career - I used VB from the very beginning. That's an incredible thing to be a part of. So, it's a pleasure to write useful code (and still using a "Visual" product!) for someone who helped kick it all off.
