### ISSUE TITLE
Run on boot pre login.

### ISSUE THREAD

**Issue by MonkeySaint** [drittich/DnsTube#35]
Hey I'm wondering if this can run before a login. On my servers I use the tool and I can't get it to run pre login. Some of my clients don't login and they need their VPN. Ive tried task scheduler to no avail. If you could possibly make this run as a service or have any suggestions for me that would be really helpful. Thank you.

**Comment by MonkeySaint** [comment]
So I did some more testing and I got it to run with task scheduler and it fails because of it not being able to open a gui. A command line version would be amazing if you could do that too.

**Comment by drittich** [comment]
I'll see what I can do. This is a feature I'm interested in, myself.

**Comment by MonkeySaint** [comment]
Thanks. I recently switch to cloud flare but I may need to switch back to what I was using before. If you could get it to you thank you so much.

**Comment by drittich** [comment]
I've built a [DnsTube.Console Alpha release](https://github.com/drittich/DnsTube/releases/tag/v0.9.5-alpha) , please give it a try. I plan to add a command-line parameter for the `config.json` file, but for now it will look for it in `C:\Users\[YourUserName]\AppData\Local\DnsTube\config.json`, or in the application folder if you are using a Portable version. It's easiest to configure settings with the GUI version (previous version will work for this), but if the GUI is already working for you there is no need to change any settings.

**Comment by MonkeySaint** [comment]
This is what I needed. Thank you so much. Worked as expected with task scheduler
