### ISSUE TITLE
problem about "error getting public IPv4"

### ISSUE THREAD

**Issue by GaryLee1992** [drittich/DnsTube#37]
Sorry, I got a problem after i downloaded "DnsTube-SelfContained-v0.9.4".
The problem showed "The SSL connection could not be established, see inner exception." when i manually updated my IP.
Could anyone help me? 
The screen shot of problem as following:
![image](https://user-images.githubusercontent.com/96430232/146782784-e339292d-2ce7-46b7-a8ff-93c7b3b69a4f.png)

**Thank you!!**

**Comment by drittich** [comment]
Are you able to load this URL in your browser? https://api.ipify.org/

**Comment by GaryLee1992** [comment]
> https://api.ipify.org/

yes, I can.
I get my public ip in the response page.

**Comment by GaryLee1992** [comment]
I use "http" instead of "https" in the api url.
Now, it can manually get my public IP now.
Thank you for your help.

**Comment by drittich** [comment]
Good news!
