### ISSUE TITLE
TXT record "v=spf1 ip6:"become“v=spf1 ip”

### ISSUE THREAD

**Issue by lvvfa** [drittich/DnsTube#38]
TXT record "v=spf1 ip6:"become“v=spf1 ip”
lack“6:”  
The IPv6 address of the last segment is repeated. The IPv6 address of segment 8 becomes segment 9 and ": 88ab" becomes ": 88ab: 88ab"

**Comment by drittich** [comment]
Thanks for reporting the issue. I'll try to take a look soon.

**Comment by drittich** [comment]
This should be fixed in [Release v0.9.6](https://github.com/drittich/DnsTube/releases/tag/v0.9.6). Please give it a try and let me know.

**Comment by lvvfa** [comment]
Thank you!

                 The problem of duplicate IPv6 address in the last segment of TXT record has been fixed and solved.

                 TXT record "v = spf1 ip6:" becomes "v = spf1 $", "ip6:" becomes "$"

**Comment by drittich** [comment]
Continuing in https://github.com/drittich/DnsTube/issues/39
