### ISSUE TITLE
 Thank you!         TXT record "v=spf1 ip6:" becomes "v=spf1 $2", "ip6:" becomes "$2"

### ISSUE THREAD

**Issue by lvvfa** [drittich/DnsTube#39]
Thank you!
             The problem of duplicate IPv6 address in the last segment of TXT record has been fixed and solved.
             TXT record "v=spf1 ip6:" becomes "v=spf1 $2", "ip6:" becomes "$2"

**Comment by drittich** [comment]
Sorry about that, should be fixed in this release: https://github.com/drittich/DnsTube/releases/tag/v0.9.7.

**Comment by lvvfa** [comment]
Thank you!
You quickly solved all the problems I found

**Comment by drittich** [comment]
Happy to help!
