### ISSUE TITLE
Use 24 hours time format

### ISSUE THREAD

**Issue by mrintrepide** [drittich/DnsTube#40]
Hi

Can you use 24 hours time format ? I can send you a PR for this.

12h format not display correctly on 24h systems.
![Screenshot_20220719_133805](https://user-images.githubusercontent.com/40322493/179741800-82ec91b9-b409-4eac-b806-aeb62d4d57d4.png)

With my PR in civilized world
![Screenshot_20220719_134359](https://user-images.githubusercontent.com/40322493/179742417-f31c1f34-afc2-4580-a46e-df8320895b66.png)

**Comment by drittich** [comment]
Fixed in [latest release](https://github.com/drittich/DnsTube/releases).
