### ISSUE TITLE
Automatic DNS update 

### ISSUE THREAD

**Issue by SinaBina** [drittich/DnsTube#42]
Hi
Please add an option to update DNS records automatically on program launch.Currently the first updates happens only after N minutes set by update interval.

Thanks

**Comment by drittich** [comment]
Thanks for the report. I thought it did that, but maybe not! I'll check it out.

**Comment by drittich** [comment]
Fixed in [release v0.9.9](https://github.com/drittich/DnsTube/releases/tag/v0.9.9)
