### ISSUE TITLE
Start a application at system start without login

### ISSUE THREAD

**Issue by fantasjr** [drittich/DnsTube#43]
pls make this application start as a service!

**Comment by drittich** [comment]
Thanks for the comment. This is definitely on the to do list, and actually largely implemented. Just need to find the time to get it to the finish line.

**Comment by drittich** [comment]
I've started this up again. Expect an alpha release in not too long.

**Comment by drittich** [comment]
I've got an alpha release if you're interest in testing it.

**Comment by fantasjr** [comment]
thanks

**Comment by drittich** [comment]
Give this a try. There are a few rough edges, but the basics should be working OK. Unzip and view the `README.md` for installation instructions. You'll want to have the authentication info on hand from the settings dialog of the desktop version of DnsTube you're running (if you are), but I don't recommend you run both the service and desktop versions at the same time.
[DnsTubeService v1.0a.zip](https://github.com/drittich/DnsTube/files/10007205/DnsTubeService.v1.0a.zip)

Let me know how it works for you.

**Comment by drittich** [comment]
Note there is an updated alpha release here: [Release DnsTube v2.0.0-alpha1](https://github.com/drittich/DnsTube/releases/tag/v2.0.0-alpha1)
