### ISSUE TITLE
The configuration is correct, but the IP address cannot be updated.

### ISSUE THREAD

**Issue by Choomai** [drittich/DnsTube#45]
**logs**
![image](https://user-images.githubusercontent.com/89532534/197403010-1f35e172-7a83-4cfb-8460-868ac02f0d99.png)
**config**
![image](https://user-images.githubusercontent.com/89532534/197403355-cc369add-2c0b-478f-8947-dfdd8573c066.png)
**API token**
![image](https://user-images.githubusercontent.com/89532534/197403068-affcdd03-eff7-46b5-89aa-532e7a2e50b3.png)

**Comment by drittich** [comment]
Unfortunately there is nothing I can do about this. See https://community.cloudflare.com/t/why-wont-cloudflare-recognize-my-tk-domain-like-it-did-in-the-past/323965. If you can use another top-level domain, that's one possible solution. Once it starts working with Cloudflare, DnsTube will start working too.
