### ISSUE TITLE
When installing in windows showing error 1053

### ISSUE THREAD

**Issue by itsmejomijohn** [drittich/DnsTube#46]
**when i try to install the latest version showing following error**
-----------------------------------------------
PS E:\ddns> .\install-service.bat
Creating service...
[SC] CreateService SUCCESS
[SC] ChangeServiceConfig2 SUCCESS
Starting service...
[SC] StartService FAILED 1053:

The service did not respond to the start or control request in a timely fashion.

------------------------------------------

**Comment by drittich** [comment]
Thanks for giving it a try. You may be the first...

I just tested the x64 install on a laptop I have not installed it on before and it worked fine, so a little more information from you would help me narrow it down:

1. What version did you try, the x64 or x86 version?
2. What OS are you installing it on?
3. Do you have the .NET 7 SDK installed already? If not, try installing it from here and do the install again: https://dotnet.microsoft.com/en-us/download/dotnet/7.0 - you probably want the Windows x64 version if running Windows 10/11
4. What does the output of the command `sc query "DnsTube Service"` show? 
5. Run Windows Event Viewer and examine "Windows Logs/Application". Do you see any errors/warning in there at the time you tried the install ? Look in the Source column for "DnsTube Service" to find relevant events.

**Comment by Marvel0us7** [comment]
Installing .NET 7 SDK fixed the error for me on Windows 11 22H2 64-Bit

**Comment by drittich** [comment]
Thanks for the info. Added a check for this in the install script in commit https://github.com/drittich/DnsTube/commit/ad59a3c0f07e542d16eee88847d9548a61532cdb. Will go out with the next release.
