### ISSUE TITLE
how to start it with windows without login on?

### ISSUE THREAD

**Issue by raykai** [drittich/DnsTube#5]
is there a way to get it working as a service?
is there a way to set it up in a way that when we login we get the program window minimized?

**Comment by raykai** [comment]
so far this is the only program out there that is working with cloudflare.

**Comment by drittich** [comment]
You can use a shortcut in the Windows Startup folder set to Minimized. I'll add this as a setting at some point. I'm planning on converting to a service too, just distracted with other projects at the moment.

**Comment by drittich** [comment]
>is there a way to set it up in a way that when we login we get the program window minimized
The latest release v0.3.4 has a setting to launch the application minimized.

**Comment by kurtnelle** [comment]
@XXLPoseidon , you can use windows task scheduler to start it.
