### ISSUE TITLE
[Support] IPv6 DDNS support.

### ISSUE THREAD

**Issue by vgxbj** [drittich/DnsTube#6]
Nice tool! Do you have any plan to support IPv6?

**Comment by drittich** [comment]
No current plans for that. Happy to receive a PR for that though.

**Comment by leviacn** [comment]
can u support ipv6？

**Comment by drittich** [comment]
I'll look into adding this in the next day or so, but my modem does not support ipv6. Maybe you can do some testing for me?

**Comment by leviacn** [comment]
sure, anytime.

**Comment by vgxbj** [comment]
> I'll look into adding this in the next day or so, but my modem does not support ipv6. Maybe you can do some testing for me?

Great, thank u! I could help as well :)

**Comment by drittich** [comment]
Beta version with support for IPv6 has been released. Let me know how it works for you: https://github.com/drittich/DnsTube/releases/tag/v0.6.0b
