### ISSUE TITLE
Error 400: Bad Request on valid key

### ISSUE THREAD

**Issue by aytimothy** [drittich/DnsTube#7]
I'm not sure if it's me or the program, but I'm getting non-crashing Error 400s.

Could it have been that the API endpoints has been changed?

![Screenshot_20191219_165136_com google chromeremotedesktop](https://user-images.githubusercontent.com/7418834/71159153-19aabe80-2280-11ea-9a45-745ab877f1b1.jpg)

NB: Was remoting into the computer, but that shouldn't be an issue.

**Comment by aytimothy** [comment]
Tried an invalid key so it could be the program requesting the wrong endpoints?

**Comment by drittich** [comment]
I can't reproduce here. Try hitting the API from the command line. Download curl from https://curl.haxx.se/windows/ and try this command:

```curl.exe -X GET "https://api.cloudflare.com/client/v4/zones?status=active&page=1&per_page=50&order=name&direction=asc&match=all" -H "Content-Type:application/json" -H "X-Auth-Email: <YOUR_EMAIL>" -H "X-Auth-Key: <YOUR_API_Key>"```

**Comment by aytimothy** [comment]
My key's reported as valid using that, but it's still getting bad requests.

The request I got was:

```json
{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
```

**Comment by aytimothy** [comment]
Made a few edits; the first iteration was nonsense, this should now make more sense.

**Comment by drittich** [comment]
Just to be clear, this was working before with the same API key? I can successfully run the curl command I provided. You might try generating a new API key, just in case there is something funny going on on the Cloudflare side.

**Comment by drittich** [comment]
Also, I DON"T have success running the verify command you gave. When I run
```"curl.exe" -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" -H "Authorization: Bearer <MY_API_KEY>" -H "Content-Type:application/json"```
I get
```{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null}```

So, I really don't know what's going on here.

**Comment by aytimothy** [comment]
I've generated a new key, the `curl` command Cloudflare provided works, but yours is returning "invalid headers". I copy-pasted it as-is, but ran it via Linux.

![image](https://user-images.githubusercontent.com/7418834/71184168-4b3d7d00-22b4-11ea-9a63-36a2859c5187.png)

```
aytimothy@AYTIMOTHYPC-3:~$ curl -X GET "https://api.cloudflare.com/client/v4/zones?status=active&page=1&per_page=50&order=name&direction=asc&match=all" -H "Content-Type:application/json" -H "X-Auth-Email: <EMAIL>" -H "X-Auth-Key: <API KEY>"
{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
```

**Comment by aytimothy** [comment]
I found the problem - Cloudflare *also* calls "API Tokens", "API Keys". That must be where I'm confusing...

Tokens are alphanumeric, while keys are Hexdecimal (in string form).

![image](https://user-images.githubusercontent.com/7418834/71184546-df0f4900-22b4-11ea-9e9d-5e0c3c59423d.png)

*Taken from https://dash.cloudflare.com/<SESSION ID>/profile/api-tokens*

**Comment by drittich** [comment]
Well. that's annoying! Glad you got it sorted.

**Comment by EkajArmstro** [comment]
Ran into the same issue. Would be nice if there was API Token support instead of just API Key support. But still great program!!

**Comment by drittich** [comment]
Support for API tokens added in release v0.5.0 https://github.com/drittich/DnsTube/releases/tag/v0.5.0
