### ISSUE TITLE
Proxied problems.

### ISSUE THREAD

**Issue by HappyAreaBean** [drittich/DnsTube#8]
Every time update ip is not proxied please fix it.
or add a option to disable / enable it. Please!

**Comment by drittich** [comment]
I don't understand the issue, can you describe what is happening?

**Comment by trunghuydj** [comment]
@drittich is cloudflare has hide IP ( using Proxy/proxied ) . i need add proxied disable / enable
![image](https://user-images.githubusercontent.com/30363673/72942567-551c3980-3da6-11ea-912d-daa5d881fd14.png)

**Comment by HappyAreaBean** [comment]
> @drittich is cloudflare has hide IP ( using Proxy/proxied ) . i need add proxied disable / enable
> ![image](https://user-images.githubusercontent.com/30363673/72942567-551c3980-3da6-11ea-912d-daa5d881fd14.png)

Oh. that is what i want to say.

**Comment by drittich** [comment]
Got it, I'll try to add support for that shortly.

**Comment by drittich** [comment]
Fixed in [v0.4.0](https://github.com/drittich/DnsTube/releases/tag/v0.4.0)
